name: Release LKL

on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: "Run ID of the desired CI run to download liblkl artifacts from"
        required: true

permissions:
  contents: write

jobs:
  release-lkl:
    name: Release LKL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-lkl.yaml
          workflow_conclusion: success
          run_id: ${{ github.event.inputs.ci_run_id }}
          path: artifacts
          skip_unpack: true

      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
            keep_latest: 0
            delete_tags: true
            delete_tag_pattern: last-liblkl-ci
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for 3s
        run: |
          # prevent github to think our release already exists and create us a draft
          sleep 3

      - name: Create release (Release)
        uses: softprops/action-gh-release@v1
        with:
            name: Last liblkl CI build
            target_commitish: main
            tag_name: last-liblkl-ci
            draft: false
            prerelease: false
            fail_on_unmatched_files: true
            files: |
              artifacts/liblkl_*.zip
